"use client";

import Document, { DocumentContext, Head, Html } from "next/document";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

interface RootLayoutTypes {
  children: React.ReactNode;
}

// const RootLayout = ({ children }: RootLayoutTypes) => {
//   return (
//     <html lang="en">
//       <head></head>
//       <body>{children}</body>
//     </html>
//   )
// }

// RootLayout.getInitialProps = async (ctx: DocumentContext) => {
//   const initialProps = await Document.getInitialProps(ctx);

//   const { req } = ctx;

//   const nonce = req?.headers['X-Request-Id'] || req?.headers['x-request-id'] || '';

//   return { ...initialProps, nonce };
// };

class RootLayout extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);
    console.log('tut', initialProps)
  }
 
  render() {
    return (
      <Html>
        <Head></Head>
      </Html>
    )
  }
}
 

export default RootLayout;
